//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiExpress.WebServiceProveedor {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicios/", ConfigurationName="WebServiceProveedor.WebServiceProveedor")]
    public interface WebServiceProveedor {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/WebServiceProveedor/helloRequest", ReplyAction="http://servicios/WebServiceProveedor/helloResponse")]
        ServiExpress.WebServiceProveedor.helloResponse hello(ServiExpress.WebServiceProveedor.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/WebServiceProveedor/helloRequest", ReplyAction="http://servicios/WebServiceProveedor/helloResponse")]
        System.Threading.Tasks.Task<ServiExpress.WebServiceProveedor.helloResponse> helloAsync(ServiExpress.WebServiceProveedor.helloRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hello", Namespace="http://servicios/", Order=0)]
        public ServiExpress.WebServiceProveedor.helloRequestBody Body;
        
        public helloRequest() {
        }
        
        public helloRequest(ServiExpress.WebServiceProveedor.helloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public helloRequestBody() {
        }
        
        public helloRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="helloResponse", Namespace="http://servicios/", Order=0)]
        public ServiExpress.WebServiceProveedor.helloResponseBody Body;
        
        public helloResponse() {
        }
        
        public helloResponse(ServiExpress.WebServiceProveedor.helloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public helloResponseBody() {
        }
        
        public helloResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceProveedorChannel : ServiExpress.WebServiceProveedor.WebServiceProveedor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceProveedorClient : System.ServiceModel.ClientBase<ServiExpress.WebServiceProveedor.WebServiceProveedor>, ServiExpress.WebServiceProveedor.WebServiceProveedor {
        
        public WebServiceProveedorClient() {
        }
        
        public WebServiceProveedorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceProveedorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceProveedorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceProveedorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiExpress.WebServiceProveedor.helloResponse ServiExpress.WebServiceProveedor.WebServiceProveedor.hello(ServiExpress.WebServiceProveedor.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            ServiExpress.WebServiceProveedor.helloRequest inValue = new ServiExpress.WebServiceProveedor.helloRequest();
            inValue.Body = new ServiExpress.WebServiceProveedor.helloRequestBody();
            inValue.Body.name = name;
            ServiExpress.WebServiceProveedor.helloResponse retVal = ((ServiExpress.WebServiceProveedor.WebServiceProveedor)(this)).hello(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiExpress.WebServiceProveedor.helloResponse> ServiExpress.WebServiceProveedor.WebServiceProveedor.helloAsync(ServiExpress.WebServiceProveedor.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiExpress.WebServiceProveedor.helloResponse> helloAsync(string name) {
            ServiExpress.WebServiceProveedor.helloRequest inValue = new ServiExpress.WebServiceProveedor.helloRequest();
            inValue.Body = new ServiExpress.WebServiceProveedor.helloRequestBody();
            inValue.Body.name = name;
            return ((ServiExpress.WebServiceProveedor.WebServiceProveedor)(this)).helloAsync(inValue);
        }
    }
}
