//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiExpress.WebServiceEmpleado {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicios/", ConfigurationName="WebServiceEmpleado.WebServiceEmpleado")]
    public interface WebServiceEmpleado {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/WebServiceEmpleado/GetAtencionesRequest", ReplyAction="http://servicios/WebServiceEmpleado/GetAtencionesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiExpress.WebServiceEmpleado.GetAtencionesResponse GetAtenciones(ServiExpress.WebServiceEmpleado.GetAtencionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/WebServiceEmpleado/GetAtencionesRequest", ReplyAction="http://servicios/WebServiceEmpleado/GetAtencionesResponse")]
        System.Threading.Tasks.Task<ServiExpress.WebServiceEmpleado.GetAtencionesResponse> GetAtencionesAsync(ServiExpress.WebServiceEmpleado.GetAtencionesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/WebServiceEmpleado/GetAtencionRequest", ReplyAction="http://servicios/WebServiceEmpleado/GetAtencionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiExpress.WebServiceEmpleado.GetAtencionResponse GetAtencion(ServiExpress.WebServiceEmpleado.GetAtencionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/WebServiceEmpleado/GetAtencionRequest", ReplyAction="http://servicios/WebServiceEmpleado/GetAtencionResponse")]
        System.Threading.Tasks.Task<ServiExpress.WebServiceEmpleado.GetAtencionResponse> GetAtencionAsync(ServiExpress.WebServiceEmpleado.GetAtencionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/WebServiceEmpleado/GetProductosRequest", ReplyAction="http://servicios/WebServiceEmpleado/GetProductosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiExpress.WebServiceEmpleado.GetProductosResponse GetProductos(ServiExpress.WebServiceEmpleado.GetProductosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/WebServiceEmpleado/GetProductosRequest", ReplyAction="http://servicios/WebServiceEmpleado/GetProductosResponse")]
        System.Threading.Tasks.Task<ServiExpress.WebServiceEmpleado.GetProductosResponse> GetProductosAsync(ServiExpress.WebServiceEmpleado.GetProductosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/WebServiceEmpleado/RegistrarVentaRequest", ReplyAction="http://servicios/WebServiceEmpleado/RegistrarVentaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiExpress.WebServiceEmpleado.RegistrarVentaResponse RegistrarVenta(ServiExpress.WebServiceEmpleado.RegistrarVentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/WebServiceEmpleado/RegistrarVentaRequest", ReplyAction="http://servicios/WebServiceEmpleado/RegistrarVentaResponse")]
        System.Threading.Tasks.Task<ServiExpress.WebServiceEmpleado.RegistrarVentaResponse> RegistrarVentaAsync(ServiExpress.WebServiceEmpleado.RegistrarVentaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/WebServiceEmpleado/ActualizarProductosRequest", ReplyAction="http://servicios/WebServiceEmpleado/ActualizarProductosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiExpress.WebServiceEmpleado.ActualizarProductosResponse ActualizarProductos(ServiExpress.WebServiceEmpleado.ActualizarProductosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/WebServiceEmpleado/ActualizarProductosRequest", ReplyAction="http://servicios/WebServiceEmpleado/ActualizarProductosResponse")]
        System.Threading.Tasks.Task<ServiExpress.WebServiceEmpleado.ActualizarProductosResponse> ActualizarProductosAsync(ServiExpress.WebServiceEmpleado.ActualizarProductosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/WebServiceEmpleado/GetTipoDeProductoRequest", ReplyAction="http://servicios/WebServiceEmpleado/GetTipoDeProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiExpress.WebServiceEmpleado.GetTipoDeProductoResponse GetTipoDeProducto(ServiExpress.WebServiceEmpleado.GetTipoDeProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/WebServiceEmpleado/GetTipoDeProductoRequest", ReplyAction="http://servicios/WebServiceEmpleado/GetTipoDeProductoResponse")]
        System.Threading.Tasks.Task<ServiExpress.WebServiceEmpleado.GetTipoDeProductoResponse> GetTipoDeProductoAsync(ServiExpress.WebServiceEmpleado.GetTipoDeProductoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/WebServiceEmpleado/RegistrarAtencionRequest", ReplyAction="http://servicios/WebServiceEmpleado/RegistrarAtencionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiExpress.WebServiceEmpleado.RegistrarAtencionResponse RegistrarAtencion(ServiExpress.WebServiceEmpleado.RegistrarAtencionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/WebServiceEmpleado/RegistrarAtencionRequest", ReplyAction="http://servicios/WebServiceEmpleado/RegistrarAtencionResponse")]
        System.Threading.Tasks.Task<ServiExpress.WebServiceEmpleado.RegistrarAtencionResponse> RegistrarAtencionAsync(ServiExpress.WebServiceEmpleado.RegistrarAtencionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/WebServiceEmpleado/GetTipoDeServiciosRequest", ReplyAction="http://servicios/WebServiceEmpleado/GetTipoDeServiciosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiExpress.WebServiceEmpleado.GetTipoDeServiciosResponse GetTipoDeServicios(ServiExpress.WebServiceEmpleado.GetTipoDeServiciosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/WebServiceEmpleado/GetTipoDeServiciosRequest", ReplyAction="http://servicios/WebServiceEmpleado/GetTipoDeServiciosResponse")]
        System.Threading.Tasks.Task<ServiExpress.WebServiceEmpleado.GetTipoDeServiciosResponse> GetTipoDeServiciosAsync(ServiExpress.WebServiceEmpleado.GetTipoDeServiciosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/WebServiceEmpleado/GetTipoDeDocumentoRequest", ReplyAction="http://servicios/WebServiceEmpleado/GetTipoDeDocumentoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiExpress.WebServiceEmpleado.GetTipoDeDocumentoResponse GetTipoDeDocumento(ServiExpress.WebServiceEmpleado.GetTipoDeDocumentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/WebServiceEmpleado/GetTipoDeDocumentoRequest", ReplyAction="http://servicios/WebServiceEmpleado/GetTipoDeDocumentoResponse")]
        System.Threading.Tasks.Task<ServiExpress.WebServiceEmpleado.GetTipoDeDocumentoResponse> GetTipoDeDocumentoAsync(ServiExpress.WebServiceEmpleado.GetTipoDeDocumentoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/WebServiceEmpleado/GetVentasEmpleadoRequest", ReplyAction="http://servicios/WebServiceEmpleado/GetVentasEmpleadoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiExpress.WebServiceEmpleado.GetVentasEmpleadoResponse GetVentasEmpleado(ServiExpress.WebServiceEmpleado.GetVentasEmpleadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/WebServiceEmpleado/GetVentasEmpleadoRequest", ReplyAction="http://servicios/WebServiceEmpleado/GetVentasEmpleadoResponse")]
        System.Threading.Tasks.Task<ServiExpress.WebServiceEmpleado.GetVentasEmpleadoResponse> GetVentasEmpleadoAsync(ServiExpress.WebServiceEmpleado.GetVentasEmpleadoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/WebServiceEmpleado/PagarRequest", ReplyAction="http://servicios/WebServiceEmpleado/PagarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiExpress.WebServiceEmpleado.PagarResponse Pagar(ServiExpress.WebServiceEmpleado.PagarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/WebServiceEmpleado/PagarRequest", ReplyAction="http://servicios/WebServiceEmpleado/PagarResponse")]
        System.Threading.Tasks.Task<ServiExpress.WebServiceEmpleado.PagarResponse> PagarAsync(ServiExpress.WebServiceEmpleado.PagarRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios/")]
    public partial class atenciones : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fecha_reservaField;
        
        private string hora_reservaField;
        
        private int id_atencionField;
        
        private int id_estadoField;
        
        private int id_reservaField;
        
        private string patenteField;
        
        private string sucursalField;
        
        private string usuario_rutField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fecha_reserva {
            get {
                return this.fecha_reservaField;
            }
            set {
                this.fecha_reservaField = value;
                this.RaisePropertyChanged("fecha_reserva");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string hora_reserva {
            get {
                return this.hora_reservaField;
            }
            set {
                this.hora_reservaField = value;
                this.RaisePropertyChanged("hora_reserva");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int id_atencion {
            get {
                return this.id_atencionField;
            }
            set {
                this.id_atencionField = value;
                this.RaisePropertyChanged("id_atencion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id_estado {
            get {
                return this.id_estadoField;
            }
            set {
                this.id_estadoField = value;
                this.RaisePropertyChanged("id_estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int id_reserva {
            get {
                return this.id_reservaField;
            }
            set {
                this.id_reservaField = value;
                this.RaisePropertyChanged("id_reserva");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string patente {
            get {
                return this.patenteField;
            }
            set {
                this.patenteField = value;
                this.RaisePropertyChanged("patente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string sucursal {
            get {
                return this.sucursalField;
            }
            set {
                this.sucursalField = value;
                this.RaisePropertyChanged("sucursal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string usuario_rut {
            get {
                return this.usuario_rutField;
            }
            set {
                this.usuario_rutField = value;
                this.RaisePropertyChanged("usuario_rut");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios/")]
    public partial class estadoDeVenta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string estadoField;
        
        private int idEstadoDeVentaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idEstadoDeVenta {
            get {
                return this.idEstadoDeVentaField;
            }
            set {
                this.idEstadoDeVentaField = value;
                this.RaisePropertyChanged("idEstadoDeVenta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios/")]
    public partial class ventas : object, System.ComponentModel.INotifyPropertyChanged {
        
        private estadoDeVenta estadoDeVentaField;
        
        private string fechaField;
        
        private int idAtencionField;
        
        private int idDocumentoField;
        
        private int id_ventaField;
        
        private int montoAPagarField;
        
        private int montoPagadoField;
        
        private string rutField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public estadoDeVenta estadoDeVenta {
            get {
                return this.estadoDeVentaField;
            }
            set {
                this.estadoDeVentaField = value;
                this.RaisePropertyChanged("estadoDeVenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idAtencion {
            get {
                return this.idAtencionField;
            }
            set {
                this.idAtencionField = value;
                this.RaisePropertyChanged("idAtencion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idDocumento {
            get {
                return this.idDocumentoField;
            }
            set {
                this.idDocumentoField = value;
                this.RaisePropertyChanged("idDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int id_venta {
            get {
                return this.id_ventaField;
            }
            set {
                this.id_ventaField = value;
                this.RaisePropertyChanged("id_venta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int montoAPagar {
            get {
                return this.montoAPagarField;
            }
            set {
                this.montoAPagarField = value;
                this.RaisePropertyChanged("montoAPagar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int montoPagado {
            get {
                return this.montoPagadoField;
            }
            set {
                this.montoPagadoField = value;
                this.RaisePropertyChanged("montoPagado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("rut");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios/")]
    public partial class tipoDeDocumento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string documentoField;
        
        private int id_tipo_de_documentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
                this.RaisePropertyChanged("documento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id_tipo_de_documento {
            get {
                return this.id_tipo_de_documentoField;
            }
            set {
                this.id_tipo_de_documentoField = value;
                this.RaisePropertyChanged("id_tipo_de_documento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios/")]
    public partial class tipoDeProducto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idTipoDeProductoField;
        
        private string productoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idTipoDeProducto {
            get {
                return this.idTipoDeProductoField;
            }
            set {
                this.idTipoDeProductoField = value;
                this.RaisePropertyChanged("idTipoDeProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
                this.RaisePropertyChanged("producto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios/")]
    public partial class producto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private string fechaVencimientoField;
        
        private int idOrdenDePedidoField;
        
        private int idProductoField;
        
        private int idTipoDeProductoField;
        
        private string marcaField;
        
        private int precioCompraField;
        
        private int precioVentaField;
        
        private string rutProveedorField;
        
        private int stockField;
        
        private int stockCriticoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fechaVencimiento {
            get {
                return this.fechaVencimientoField;
            }
            set {
                this.fechaVencimientoField = value;
                this.RaisePropertyChanged("fechaVencimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idOrdenDePedido {
            get {
                return this.idOrdenDePedidoField;
            }
            set {
                this.idOrdenDePedidoField = value;
                this.RaisePropertyChanged("idOrdenDePedido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idProducto {
            get {
                return this.idProductoField;
            }
            set {
                this.idProductoField = value;
                this.RaisePropertyChanged("idProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idTipoDeProducto {
            get {
                return this.idTipoDeProductoField;
            }
            set {
                this.idTipoDeProductoField = value;
                this.RaisePropertyChanged("idTipoDeProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
                this.RaisePropertyChanged("marca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int precioCompra {
            get {
                return this.precioCompraField;
            }
            set {
                this.precioCompraField = value;
                this.RaisePropertyChanged("precioCompra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int precioVenta {
            get {
                return this.precioVentaField;
            }
            set {
                this.precioVentaField = value;
                this.RaisePropertyChanged("precioVenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string rutProveedor {
            get {
                return this.rutProveedorField;
            }
            set {
                this.rutProveedorField = value;
                this.RaisePropertyChanged("rutProveedor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int stock {
            get {
                return this.stockField;
            }
            set {
                this.stockField = value;
                this.RaisePropertyChanged("stock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int stockCritico {
            get {
                return this.stockCriticoField;
            }
            set {
                this.stockCriticoField = value;
                this.RaisePropertyChanged("stockCritico");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios/")]
    public partial class tipoDeServicio : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int id_servicioField;
        
        private string servicioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id_servicio {
            get {
                return this.id_servicioField;
            }
            set {
                this.id_servicioField = value;
                this.RaisePropertyChanged("id_servicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string servicio {
            get {
                return this.servicioField;
            }
            set {
                this.servicioField = value;
                this.RaisePropertyChanged("servicio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios/")]
    public partial class estadoDeAtencion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string estadoField;
        
        private int idEstadoDeAtencionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idEstadoDeAtencion {
            get {
                return this.idEstadoDeAtencionField;
            }
            set {
                this.idEstadoDeAtencionField = value;
                this.RaisePropertyChanged("idEstadoDeAtencion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios/")]
    public partial class atencion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private estadoDeAtencion estado_de_atencionField;
        
        private string fecha_atencionField;
        
        private string hora_atencionField;
        
        private int id_atencionField;
        
        private int id_reservaField;
        
        private string patenteField;
        
        private tipoDeServicio tipo_de_servicioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public estadoDeAtencion estado_de_atencion {
            get {
                return this.estado_de_atencionField;
            }
            set {
                this.estado_de_atencionField = value;
                this.RaisePropertyChanged("estado_de_atencion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fecha_atencion {
            get {
                return this.fecha_atencionField;
            }
            set {
                this.fecha_atencionField = value;
                this.RaisePropertyChanged("fecha_atencion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string hora_atencion {
            get {
                return this.hora_atencionField;
            }
            set {
                this.hora_atencionField = value;
                this.RaisePropertyChanged("hora_atencion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id_atencion {
            get {
                return this.id_atencionField;
            }
            set {
                this.id_atencionField = value;
                this.RaisePropertyChanged("id_atencion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int id_reserva {
            get {
                return this.id_reservaField;
            }
            set {
                this.id_reservaField = value;
                this.RaisePropertyChanged("id_reserva");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string patente {
            get {
                return this.patenteField;
            }
            set {
                this.patenteField = value;
                this.RaisePropertyChanged("patente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public tipoDeServicio tipo_de_servicio {
            get {
                return this.tipo_de_servicioField;
            }
            set {
                this.tipo_de_servicioField = value;
                this.RaisePropertyChanged("tipo_de_servicio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAtenciones", WrapperNamespace="http://servicios/", IsWrapped=true)]
    public partial class GetAtencionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id_sucursal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string filtro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string valorFiltro;
        
        public GetAtencionesRequest() {
        }
        
        public GetAtencionesRequest(string id_sucursal, string filtro, string valorFiltro) {
            this.id_sucursal = id_sucursal;
            this.filtro = filtro;
            this.valorFiltro = valorFiltro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAtencionesResponse", WrapperNamespace="http://servicios/", IsWrapped=true)]
    public partial class GetAtencionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public ServiExpress.WebServiceEmpleado.atenciones[] @return;
        
        public GetAtencionesResponse() {
        }
        
        public GetAtencionesResponse(ServiExpress.WebServiceEmpleado.atenciones[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAtencion", WrapperNamespace="http://servicios/", IsWrapped=true)]
    public partial class GetAtencionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idReserva;
        
        public GetAtencionRequest() {
        }
        
        public GetAtencionRequest(int idReserva) {
            this.idReserva = idReserva;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAtencionResponse", WrapperNamespace="http://servicios/", IsWrapped=true)]
    public partial class GetAtencionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiExpress.WebServiceEmpleado.atencion @return;
        
        public GetAtencionResponse() {
        }
        
        public GetAtencionResponse(ServiExpress.WebServiceEmpleado.atencion @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProductos", WrapperNamespace="http://servicios/", IsWrapped=true)]
    public partial class GetProductosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTipoDeProducto;
        
        public GetProductosRequest() {
        }
        
        public GetProductosRequest(int idTipoDeProducto) {
            this.idTipoDeProducto = idTipoDeProducto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProductosResponse", WrapperNamespace="http://servicios/", IsWrapped=true)]
    public partial class GetProductosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public ServiExpress.WebServiceEmpleado.producto[] @return;
        
        public GetProductosResponse() {
        }
        
        public GetProductosResponse(ServiExpress.WebServiceEmpleado.producto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrarVenta", WrapperNamespace="http://servicios/", IsWrapped=true)]
    public partial class RegistrarVentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idAtencion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idVenta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int montoAPagar;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int montoPagado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaVenta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEstadoVenta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuarioRut;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idDocumento;
        
        public RegistrarVentaRequest() {
        }
        
        public RegistrarVentaRequest(int idAtencion, int idVenta, int montoAPagar, int montoPagado, string fechaVenta, int idEstadoVenta, string usuarioRut, int idDocumento) {
            this.idAtencion = idAtencion;
            this.idVenta = idVenta;
            this.montoAPagar = montoAPagar;
            this.montoPagado = montoPagado;
            this.fechaVenta = fechaVenta;
            this.idEstadoVenta = idEstadoVenta;
            this.usuarioRut = usuarioRut;
            this.idDocumento = idDocumento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrarVentaResponse", WrapperNamespace="http://servicios/", IsWrapped=true)]
    public partial class RegistrarVentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] @return;
        
        public RegistrarVentaResponse() {
        }
        
        public RegistrarVentaResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizarProductos", WrapperNamespace="http://servicios/", IsWrapped=true)]
    public partial class ActualizarProductosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int VentasIdVenta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idProductoVendido;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int totalAPagar;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idProducto;
        
        public ActualizarProductosRequest() {
        }
        
        public ActualizarProductosRequest(int VentasIdVenta, int idProductoVendido, int cantidad, int totalAPagar, int idProducto) {
            this.VentasIdVenta = VentasIdVenta;
            this.idProductoVendido = idProductoVendido;
            this.cantidad = cantidad;
            this.totalAPagar = totalAPagar;
            this.idProducto = idProducto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizarProductosResponse", WrapperNamespace="http://servicios/", IsWrapped=true)]
    public partial class ActualizarProductosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] @return;
        
        public ActualizarProductosResponse() {
        }
        
        public ActualizarProductosResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTipoDeProducto", WrapperNamespace="http://servicios/", IsWrapped=true)]
    public partial class GetTipoDeProductoRequest {
        
        public GetTipoDeProductoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTipoDeProductoResponse", WrapperNamespace="http://servicios/", IsWrapped=true)]
    public partial class GetTipoDeProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public ServiExpress.WebServiceEmpleado.tipoDeProducto[] @return;
        
        public GetTipoDeProductoResponse() {
        }
        
        public GetTipoDeProductoResponse(ServiExpress.WebServiceEmpleado.tipoDeProducto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrarAtencion", WrapperNamespace="http://servicios/", IsWrapped=true)]
    public partial class RegistrarAtencionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaAtencion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string horaAtencion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTipoDeServicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idReserva;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEstadoDeAtencion;
        
        public RegistrarAtencionRequest() {
        }
        
        public RegistrarAtencionRequest(string fechaAtencion, string horaAtencion, int idTipoDeServicio, int idReserva, int idEstadoDeAtencion) {
            this.fechaAtencion = fechaAtencion;
            this.horaAtencion = horaAtencion;
            this.idTipoDeServicio = idTipoDeServicio;
            this.idReserva = idReserva;
            this.idEstadoDeAtencion = idEstadoDeAtencion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrarAtencionResponse", WrapperNamespace="http://servicios/", IsWrapped=true)]
    public partial class RegistrarAtencionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] @return;
        
        public RegistrarAtencionResponse() {
        }
        
        public RegistrarAtencionResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTipoDeServicios", WrapperNamespace="http://servicios/", IsWrapped=true)]
    public partial class GetTipoDeServiciosRequest {
        
        public GetTipoDeServiciosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTipoDeServiciosResponse", WrapperNamespace="http://servicios/", IsWrapped=true)]
    public partial class GetTipoDeServiciosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public ServiExpress.WebServiceEmpleado.tipoDeServicio[] @return;
        
        public GetTipoDeServiciosResponse() {
        }
        
        public GetTipoDeServiciosResponse(ServiExpress.WebServiceEmpleado.tipoDeServicio[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTipoDeDocumento", WrapperNamespace="http://servicios/", IsWrapped=true)]
    public partial class GetTipoDeDocumentoRequest {
        
        public GetTipoDeDocumentoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTipoDeDocumentoResponse", WrapperNamespace="http://servicios/", IsWrapped=true)]
    public partial class GetTipoDeDocumentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public ServiExpress.WebServiceEmpleado.tipoDeDocumento[] @return;
        
        public GetTipoDeDocumentoResponse() {
        }
        
        public GetTipoDeDocumentoResponse(ServiExpress.WebServiceEmpleado.tipoDeDocumento[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetVentasEmpleado", WrapperNamespace="http://servicios/", IsWrapped=true)]
    public partial class GetVentasEmpleadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string filtro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string valorFiltro;
        
        public GetVentasEmpleadoRequest() {
        }
        
        public GetVentasEmpleadoRequest(string filtro, string valorFiltro) {
            this.filtro = filtro;
            this.valorFiltro = valorFiltro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetVentasEmpleadoResponse", WrapperNamespace="http://servicios/", IsWrapped=true)]
    public partial class GetVentasEmpleadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public ServiExpress.WebServiceEmpleado.ventas[] @return;
        
        public GetVentasEmpleadoResponse() {
        }
        
        public GetVentasEmpleadoResponse(ServiExpress.WebServiceEmpleado.ventas[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Pagar", WrapperNamespace="http://servicios/", IsWrapped=true)]
    public partial class PagarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_venta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int montoPagado;
        
        public PagarRequest() {
        }
        
        public PagarRequest(int id_venta, int montoPagado) {
            this.id_venta = id_venta;
            this.montoPagado = montoPagado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PagarResponse", WrapperNamespace="http://servicios/", IsWrapped=true)]
    public partial class PagarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] @return;
        
        public PagarResponse() {
        }
        
        public PagarResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceEmpleadoChannel : ServiExpress.WebServiceEmpleado.WebServiceEmpleado, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceEmpleadoClient : System.ServiceModel.ClientBase<ServiExpress.WebServiceEmpleado.WebServiceEmpleado>, ServiExpress.WebServiceEmpleado.WebServiceEmpleado {
        
        public WebServiceEmpleadoClient() {
        }
        
        public WebServiceEmpleadoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceEmpleadoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceEmpleadoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceEmpleadoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiExpress.WebServiceEmpleado.GetAtencionesResponse ServiExpress.WebServiceEmpleado.WebServiceEmpleado.GetAtenciones(ServiExpress.WebServiceEmpleado.GetAtencionesRequest request) {
            return base.Channel.GetAtenciones(request);
        }
        
        public ServiExpress.WebServiceEmpleado.atenciones[] GetAtenciones(string id_sucursal, string filtro, string valorFiltro) {
            ServiExpress.WebServiceEmpleado.GetAtencionesRequest inValue = new ServiExpress.WebServiceEmpleado.GetAtencionesRequest();
            inValue.id_sucursal = id_sucursal;
            inValue.filtro = filtro;
            inValue.valorFiltro = valorFiltro;
            ServiExpress.WebServiceEmpleado.GetAtencionesResponse retVal = ((ServiExpress.WebServiceEmpleado.WebServiceEmpleado)(this)).GetAtenciones(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiExpress.WebServiceEmpleado.GetAtencionesResponse> ServiExpress.WebServiceEmpleado.WebServiceEmpleado.GetAtencionesAsync(ServiExpress.WebServiceEmpleado.GetAtencionesRequest request) {
            return base.Channel.GetAtencionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiExpress.WebServiceEmpleado.GetAtencionesResponse> GetAtencionesAsync(string id_sucursal, string filtro, string valorFiltro) {
            ServiExpress.WebServiceEmpleado.GetAtencionesRequest inValue = new ServiExpress.WebServiceEmpleado.GetAtencionesRequest();
            inValue.id_sucursal = id_sucursal;
            inValue.filtro = filtro;
            inValue.valorFiltro = valorFiltro;
            return ((ServiExpress.WebServiceEmpleado.WebServiceEmpleado)(this)).GetAtencionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiExpress.WebServiceEmpleado.GetAtencionResponse ServiExpress.WebServiceEmpleado.WebServiceEmpleado.GetAtencion(ServiExpress.WebServiceEmpleado.GetAtencionRequest request) {
            return base.Channel.GetAtencion(request);
        }
        
        public ServiExpress.WebServiceEmpleado.atencion GetAtencion(int idReserva) {
            ServiExpress.WebServiceEmpleado.GetAtencionRequest inValue = new ServiExpress.WebServiceEmpleado.GetAtencionRequest();
            inValue.idReserva = idReserva;
            ServiExpress.WebServiceEmpleado.GetAtencionResponse retVal = ((ServiExpress.WebServiceEmpleado.WebServiceEmpleado)(this)).GetAtencion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiExpress.WebServiceEmpleado.GetAtencionResponse> ServiExpress.WebServiceEmpleado.WebServiceEmpleado.GetAtencionAsync(ServiExpress.WebServiceEmpleado.GetAtencionRequest request) {
            return base.Channel.GetAtencionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiExpress.WebServiceEmpleado.GetAtencionResponse> GetAtencionAsync(int idReserva) {
            ServiExpress.WebServiceEmpleado.GetAtencionRequest inValue = new ServiExpress.WebServiceEmpleado.GetAtencionRequest();
            inValue.idReserva = idReserva;
            return ((ServiExpress.WebServiceEmpleado.WebServiceEmpleado)(this)).GetAtencionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiExpress.WebServiceEmpleado.GetProductosResponse ServiExpress.WebServiceEmpleado.WebServiceEmpleado.GetProductos(ServiExpress.WebServiceEmpleado.GetProductosRequest request) {
            return base.Channel.GetProductos(request);
        }
        
        public ServiExpress.WebServiceEmpleado.producto[] GetProductos(int idTipoDeProducto) {
            ServiExpress.WebServiceEmpleado.GetProductosRequest inValue = new ServiExpress.WebServiceEmpleado.GetProductosRequest();
            inValue.idTipoDeProducto = idTipoDeProducto;
            ServiExpress.WebServiceEmpleado.GetProductosResponse retVal = ((ServiExpress.WebServiceEmpleado.WebServiceEmpleado)(this)).GetProductos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiExpress.WebServiceEmpleado.GetProductosResponse> ServiExpress.WebServiceEmpleado.WebServiceEmpleado.GetProductosAsync(ServiExpress.WebServiceEmpleado.GetProductosRequest request) {
            return base.Channel.GetProductosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiExpress.WebServiceEmpleado.GetProductosResponse> GetProductosAsync(int idTipoDeProducto) {
            ServiExpress.WebServiceEmpleado.GetProductosRequest inValue = new ServiExpress.WebServiceEmpleado.GetProductosRequest();
            inValue.idTipoDeProducto = idTipoDeProducto;
            return ((ServiExpress.WebServiceEmpleado.WebServiceEmpleado)(this)).GetProductosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiExpress.WebServiceEmpleado.RegistrarVentaResponse ServiExpress.WebServiceEmpleado.WebServiceEmpleado.RegistrarVenta(ServiExpress.WebServiceEmpleado.RegistrarVentaRequest request) {
            return base.Channel.RegistrarVenta(request);
        }
        
        public string[] RegistrarVenta(int idAtencion, int idVenta, int montoAPagar, int montoPagado, string fechaVenta, int idEstadoVenta, string usuarioRut, int idDocumento) {
            ServiExpress.WebServiceEmpleado.RegistrarVentaRequest inValue = new ServiExpress.WebServiceEmpleado.RegistrarVentaRequest();
            inValue.idAtencion = idAtencion;
            inValue.idVenta = idVenta;
            inValue.montoAPagar = montoAPagar;
            inValue.montoPagado = montoPagado;
            inValue.fechaVenta = fechaVenta;
            inValue.idEstadoVenta = idEstadoVenta;
            inValue.usuarioRut = usuarioRut;
            inValue.idDocumento = idDocumento;
            ServiExpress.WebServiceEmpleado.RegistrarVentaResponse retVal = ((ServiExpress.WebServiceEmpleado.WebServiceEmpleado)(this)).RegistrarVenta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiExpress.WebServiceEmpleado.RegistrarVentaResponse> ServiExpress.WebServiceEmpleado.WebServiceEmpleado.RegistrarVentaAsync(ServiExpress.WebServiceEmpleado.RegistrarVentaRequest request) {
            return base.Channel.RegistrarVentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiExpress.WebServiceEmpleado.RegistrarVentaResponse> RegistrarVentaAsync(int idAtencion, int idVenta, int montoAPagar, int montoPagado, string fechaVenta, int idEstadoVenta, string usuarioRut, int idDocumento) {
            ServiExpress.WebServiceEmpleado.RegistrarVentaRequest inValue = new ServiExpress.WebServiceEmpleado.RegistrarVentaRequest();
            inValue.idAtencion = idAtencion;
            inValue.idVenta = idVenta;
            inValue.montoAPagar = montoAPagar;
            inValue.montoPagado = montoPagado;
            inValue.fechaVenta = fechaVenta;
            inValue.idEstadoVenta = idEstadoVenta;
            inValue.usuarioRut = usuarioRut;
            inValue.idDocumento = idDocumento;
            return ((ServiExpress.WebServiceEmpleado.WebServiceEmpleado)(this)).RegistrarVentaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiExpress.WebServiceEmpleado.ActualizarProductosResponse ServiExpress.WebServiceEmpleado.WebServiceEmpleado.ActualizarProductos(ServiExpress.WebServiceEmpleado.ActualizarProductosRequest request) {
            return base.Channel.ActualizarProductos(request);
        }
        
        public string[] ActualizarProductos(int VentasIdVenta, int idProductoVendido, int cantidad, int totalAPagar, int idProducto) {
            ServiExpress.WebServiceEmpleado.ActualizarProductosRequest inValue = new ServiExpress.WebServiceEmpleado.ActualizarProductosRequest();
            inValue.VentasIdVenta = VentasIdVenta;
            inValue.idProductoVendido = idProductoVendido;
            inValue.cantidad = cantidad;
            inValue.totalAPagar = totalAPagar;
            inValue.idProducto = idProducto;
            ServiExpress.WebServiceEmpleado.ActualizarProductosResponse retVal = ((ServiExpress.WebServiceEmpleado.WebServiceEmpleado)(this)).ActualizarProductos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiExpress.WebServiceEmpleado.ActualizarProductosResponse> ServiExpress.WebServiceEmpleado.WebServiceEmpleado.ActualizarProductosAsync(ServiExpress.WebServiceEmpleado.ActualizarProductosRequest request) {
            return base.Channel.ActualizarProductosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiExpress.WebServiceEmpleado.ActualizarProductosResponse> ActualizarProductosAsync(int VentasIdVenta, int idProductoVendido, int cantidad, int totalAPagar, int idProducto) {
            ServiExpress.WebServiceEmpleado.ActualizarProductosRequest inValue = new ServiExpress.WebServiceEmpleado.ActualizarProductosRequest();
            inValue.VentasIdVenta = VentasIdVenta;
            inValue.idProductoVendido = idProductoVendido;
            inValue.cantidad = cantidad;
            inValue.totalAPagar = totalAPagar;
            inValue.idProducto = idProducto;
            return ((ServiExpress.WebServiceEmpleado.WebServiceEmpleado)(this)).ActualizarProductosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiExpress.WebServiceEmpleado.GetTipoDeProductoResponse ServiExpress.WebServiceEmpleado.WebServiceEmpleado.GetTipoDeProducto(ServiExpress.WebServiceEmpleado.GetTipoDeProductoRequest request) {
            return base.Channel.GetTipoDeProducto(request);
        }
        
        public ServiExpress.WebServiceEmpleado.tipoDeProducto[] GetTipoDeProducto() {
            ServiExpress.WebServiceEmpleado.GetTipoDeProductoRequest inValue = new ServiExpress.WebServiceEmpleado.GetTipoDeProductoRequest();
            ServiExpress.WebServiceEmpleado.GetTipoDeProductoResponse retVal = ((ServiExpress.WebServiceEmpleado.WebServiceEmpleado)(this)).GetTipoDeProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiExpress.WebServiceEmpleado.GetTipoDeProductoResponse> ServiExpress.WebServiceEmpleado.WebServiceEmpleado.GetTipoDeProductoAsync(ServiExpress.WebServiceEmpleado.GetTipoDeProductoRequest request) {
            return base.Channel.GetTipoDeProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiExpress.WebServiceEmpleado.GetTipoDeProductoResponse> GetTipoDeProductoAsync() {
            ServiExpress.WebServiceEmpleado.GetTipoDeProductoRequest inValue = new ServiExpress.WebServiceEmpleado.GetTipoDeProductoRequest();
            return ((ServiExpress.WebServiceEmpleado.WebServiceEmpleado)(this)).GetTipoDeProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiExpress.WebServiceEmpleado.RegistrarAtencionResponse ServiExpress.WebServiceEmpleado.WebServiceEmpleado.RegistrarAtencion(ServiExpress.WebServiceEmpleado.RegistrarAtencionRequest request) {
            return base.Channel.RegistrarAtencion(request);
        }
        
        public string[] RegistrarAtencion(string fechaAtencion, string horaAtencion, int idTipoDeServicio, int idReserva, int idEstadoDeAtencion) {
            ServiExpress.WebServiceEmpleado.RegistrarAtencionRequest inValue = new ServiExpress.WebServiceEmpleado.RegistrarAtencionRequest();
            inValue.fechaAtencion = fechaAtencion;
            inValue.horaAtencion = horaAtencion;
            inValue.idTipoDeServicio = idTipoDeServicio;
            inValue.idReserva = idReserva;
            inValue.idEstadoDeAtencion = idEstadoDeAtencion;
            ServiExpress.WebServiceEmpleado.RegistrarAtencionResponse retVal = ((ServiExpress.WebServiceEmpleado.WebServiceEmpleado)(this)).RegistrarAtencion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiExpress.WebServiceEmpleado.RegistrarAtencionResponse> ServiExpress.WebServiceEmpleado.WebServiceEmpleado.RegistrarAtencionAsync(ServiExpress.WebServiceEmpleado.RegistrarAtencionRequest request) {
            return base.Channel.RegistrarAtencionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiExpress.WebServiceEmpleado.RegistrarAtencionResponse> RegistrarAtencionAsync(string fechaAtencion, string horaAtencion, int idTipoDeServicio, int idReserva, int idEstadoDeAtencion) {
            ServiExpress.WebServiceEmpleado.RegistrarAtencionRequest inValue = new ServiExpress.WebServiceEmpleado.RegistrarAtencionRequest();
            inValue.fechaAtencion = fechaAtencion;
            inValue.horaAtencion = horaAtencion;
            inValue.idTipoDeServicio = idTipoDeServicio;
            inValue.idReserva = idReserva;
            inValue.idEstadoDeAtencion = idEstadoDeAtencion;
            return ((ServiExpress.WebServiceEmpleado.WebServiceEmpleado)(this)).RegistrarAtencionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiExpress.WebServiceEmpleado.GetTipoDeServiciosResponse ServiExpress.WebServiceEmpleado.WebServiceEmpleado.GetTipoDeServicios(ServiExpress.WebServiceEmpleado.GetTipoDeServiciosRequest request) {
            return base.Channel.GetTipoDeServicios(request);
        }
        
        public ServiExpress.WebServiceEmpleado.tipoDeServicio[] GetTipoDeServicios() {
            ServiExpress.WebServiceEmpleado.GetTipoDeServiciosRequest inValue = new ServiExpress.WebServiceEmpleado.GetTipoDeServiciosRequest();
            ServiExpress.WebServiceEmpleado.GetTipoDeServiciosResponse retVal = ((ServiExpress.WebServiceEmpleado.WebServiceEmpleado)(this)).GetTipoDeServicios(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiExpress.WebServiceEmpleado.GetTipoDeServiciosResponse> ServiExpress.WebServiceEmpleado.WebServiceEmpleado.GetTipoDeServiciosAsync(ServiExpress.WebServiceEmpleado.GetTipoDeServiciosRequest request) {
            return base.Channel.GetTipoDeServiciosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiExpress.WebServiceEmpleado.GetTipoDeServiciosResponse> GetTipoDeServiciosAsync() {
            ServiExpress.WebServiceEmpleado.GetTipoDeServiciosRequest inValue = new ServiExpress.WebServiceEmpleado.GetTipoDeServiciosRequest();
            return ((ServiExpress.WebServiceEmpleado.WebServiceEmpleado)(this)).GetTipoDeServiciosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiExpress.WebServiceEmpleado.GetTipoDeDocumentoResponse ServiExpress.WebServiceEmpleado.WebServiceEmpleado.GetTipoDeDocumento(ServiExpress.WebServiceEmpleado.GetTipoDeDocumentoRequest request) {
            return base.Channel.GetTipoDeDocumento(request);
        }
        
        public ServiExpress.WebServiceEmpleado.tipoDeDocumento[] GetTipoDeDocumento() {
            ServiExpress.WebServiceEmpleado.GetTipoDeDocumentoRequest inValue = new ServiExpress.WebServiceEmpleado.GetTipoDeDocumentoRequest();
            ServiExpress.WebServiceEmpleado.GetTipoDeDocumentoResponse retVal = ((ServiExpress.WebServiceEmpleado.WebServiceEmpleado)(this)).GetTipoDeDocumento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiExpress.WebServiceEmpleado.GetTipoDeDocumentoResponse> ServiExpress.WebServiceEmpleado.WebServiceEmpleado.GetTipoDeDocumentoAsync(ServiExpress.WebServiceEmpleado.GetTipoDeDocumentoRequest request) {
            return base.Channel.GetTipoDeDocumentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiExpress.WebServiceEmpleado.GetTipoDeDocumentoResponse> GetTipoDeDocumentoAsync() {
            ServiExpress.WebServiceEmpleado.GetTipoDeDocumentoRequest inValue = new ServiExpress.WebServiceEmpleado.GetTipoDeDocumentoRequest();
            return ((ServiExpress.WebServiceEmpleado.WebServiceEmpleado)(this)).GetTipoDeDocumentoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiExpress.WebServiceEmpleado.GetVentasEmpleadoResponse ServiExpress.WebServiceEmpleado.WebServiceEmpleado.GetVentasEmpleado(ServiExpress.WebServiceEmpleado.GetVentasEmpleadoRequest request) {
            return base.Channel.GetVentasEmpleado(request);
        }
        
        public ServiExpress.WebServiceEmpleado.ventas[] GetVentasEmpleado(string filtro, string valorFiltro) {
            ServiExpress.WebServiceEmpleado.GetVentasEmpleadoRequest inValue = new ServiExpress.WebServiceEmpleado.GetVentasEmpleadoRequest();
            inValue.filtro = filtro;
            inValue.valorFiltro = valorFiltro;
            ServiExpress.WebServiceEmpleado.GetVentasEmpleadoResponse retVal = ((ServiExpress.WebServiceEmpleado.WebServiceEmpleado)(this)).GetVentasEmpleado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiExpress.WebServiceEmpleado.GetVentasEmpleadoResponse> ServiExpress.WebServiceEmpleado.WebServiceEmpleado.GetVentasEmpleadoAsync(ServiExpress.WebServiceEmpleado.GetVentasEmpleadoRequest request) {
            return base.Channel.GetVentasEmpleadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiExpress.WebServiceEmpleado.GetVentasEmpleadoResponse> GetVentasEmpleadoAsync(string filtro, string valorFiltro) {
            ServiExpress.WebServiceEmpleado.GetVentasEmpleadoRequest inValue = new ServiExpress.WebServiceEmpleado.GetVentasEmpleadoRequest();
            inValue.filtro = filtro;
            inValue.valorFiltro = valorFiltro;
            return ((ServiExpress.WebServiceEmpleado.WebServiceEmpleado)(this)).GetVentasEmpleadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiExpress.WebServiceEmpleado.PagarResponse ServiExpress.WebServiceEmpleado.WebServiceEmpleado.Pagar(ServiExpress.WebServiceEmpleado.PagarRequest request) {
            return base.Channel.Pagar(request);
        }
        
        public string[] Pagar(int id_venta, int montoPagado) {
            ServiExpress.WebServiceEmpleado.PagarRequest inValue = new ServiExpress.WebServiceEmpleado.PagarRequest();
            inValue.id_venta = id_venta;
            inValue.montoPagado = montoPagado;
            ServiExpress.WebServiceEmpleado.PagarResponse retVal = ((ServiExpress.WebServiceEmpleado.WebServiceEmpleado)(this)).Pagar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiExpress.WebServiceEmpleado.PagarResponse> ServiExpress.WebServiceEmpleado.WebServiceEmpleado.PagarAsync(ServiExpress.WebServiceEmpleado.PagarRequest request) {
            return base.Channel.PagarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiExpress.WebServiceEmpleado.PagarResponse> PagarAsync(int id_venta, int montoPagado) {
            ServiExpress.WebServiceEmpleado.PagarRequest inValue = new ServiExpress.WebServiceEmpleado.PagarRequest();
            inValue.id_venta = id_venta;
            inValue.montoPagado = montoPagado;
            return ((ServiExpress.WebServiceEmpleado.WebServiceEmpleado)(this)).PagarAsync(inValue);
        }
    }
}
