//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiExpress.WebServiceLoginUsuario {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Servicios/", ConfigurationName="WebServiceLoginUsuario.WebServiceLogin")]
    public interface WebServiceLogin {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/WebServiceLogin/WebServiceValidarLoginRequest", ReplyAction="http://Servicios/WebServiceLogin/WebServiceValidarLoginResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiExpress.WebServiceLoginUsuario.WebServiceValidarLoginResponse WebServiceValidarLogin(ServiExpress.WebServiceLoginUsuario.WebServiceValidarLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/WebServiceLogin/WebServiceValidarLoginRequest", ReplyAction="http://Servicios/WebServiceLogin/WebServiceValidarLoginResponse")]
        System.Threading.Tasks.Task<ServiExpress.WebServiceLoginUsuario.WebServiceValidarLoginResponse> WebServiceValidarLoginAsync(ServiExpress.WebServiceLoginUsuario.WebServiceValidarLoginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WebServiceValidarLogin", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class WebServiceValidarLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contraseña;
        
        public WebServiceValidarLoginRequest() {
        }
        
        public WebServiceValidarLoginRequest(string usuario, string contraseña) {
            this.usuario = usuario;
            this.contraseña = contraseña;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WebServiceValidarLoginResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class WebServiceValidarLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] @return;
        
        public WebServiceValidarLoginResponse() {
        }
        
        public WebServiceValidarLoginResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceLoginChannel : ServiExpress.WebServiceLoginUsuario.WebServiceLogin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceLoginClient : System.ServiceModel.ClientBase<ServiExpress.WebServiceLoginUsuario.WebServiceLogin>, ServiExpress.WebServiceLoginUsuario.WebServiceLogin {
        
        public WebServiceLoginClient() {
        }
        
        public WebServiceLoginClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceLoginClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceLoginClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceLoginClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiExpress.WebServiceLoginUsuario.WebServiceValidarLoginResponse ServiExpress.WebServiceLoginUsuario.WebServiceLogin.WebServiceValidarLogin(ServiExpress.WebServiceLoginUsuario.WebServiceValidarLoginRequest request) {
            return base.Channel.WebServiceValidarLogin(request);
        }
        
        public string[] WebServiceValidarLogin(string usuario, string contraseña) {
            ServiExpress.WebServiceLoginUsuario.WebServiceValidarLoginRequest inValue = new ServiExpress.WebServiceLoginUsuario.WebServiceValidarLoginRequest();
            inValue.usuario = usuario;
            inValue.contraseña = contraseña;
            ServiExpress.WebServiceLoginUsuario.WebServiceValidarLoginResponse retVal = ((ServiExpress.WebServiceLoginUsuario.WebServiceLogin)(this)).WebServiceValidarLogin(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiExpress.WebServiceLoginUsuario.WebServiceValidarLoginResponse> ServiExpress.WebServiceLoginUsuario.WebServiceLogin.WebServiceValidarLoginAsync(ServiExpress.WebServiceLoginUsuario.WebServiceValidarLoginRequest request) {
            return base.Channel.WebServiceValidarLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiExpress.WebServiceLoginUsuario.WebServiceValidarLoginResponse> WebServiceValidarLoginAsync(string usuario, string contraseña) {
            ServiExpress.WebServiceLoginUsuario.WebServiceValidarLoginRequest inValue = new ServiExpress.WebServiceLoginUsuario.WebServiceValidarLoginRequest();
            inValue.usuario = usuario;
            inValue.contraseña = contraseña;
            return ((ServiExpress.WebServiceLoginUsuario.WebServiceLogin)(this)).WebServiceValidarLoginAsync(inValue);
        }
    }
}
