//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiExpress.WebServiceUsuario {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Servicios/", ConfigurationName="WebServiceUsuario.WebServiceUsuario")]
    public interface WebServiceUsuario {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/WebServiceUsuario/WebServiceNuevoUsuarioRequest", ReplyAction="http://Servicios/WebServiceUsuario/WebServiceNuevoUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiExpress.WebServiceUsuario.WebServiceNuevoUsuarioResponse WebServiceNuevoUsuario(ServiExpress.WebServiceUsuario.WebServiceNuevoUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/WebServiceUsuario/WebServiceNuevoUsuarioRequest", ReplyAction="http://Servicios/WebServiceUsuario/WebServiceNuevoUsuarioResponse")]
        System.Threading.Tasks.Task<ServiExpress.WebServiceUsuario.WebServiceNuevoUsuarioResponse> WebServiceNuevoUsuarioAsync(ServiExpress.WebServiceUsuario.WebServiceNuevoUsuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WebServiceNuevoUsuario", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class WebServiceNuevoUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rut;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string primerNombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string segundoNombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellidoPaterno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellidoMaterno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int telefono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string direccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int comuna;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int tipoUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contraseña;
        
        public WebServiceNuevoUsuarioRequest() {
        }
        
        public WebServiceNuevoUsuarioRequest(string rut, string primerNombre, string segundoNombre, string apellidoPaterno, string apellidoMaterno, int telefono, string email, string direccion, int comuna, string nombreUsuario, int tipoUsuario, string contraseña) {
            this.rut = rut;
            this.primerNombre = primerNombre;
            this.segundoNombre = segundoNombre;
            this.apellidoPaterno = apellidoPaterno;
            this.apellidoMaterno = apellidoMaterno;
            this.telefono = telefono;
            this.email = email;
            this.direccion = direccion;
            this.comuna = comuna;
            this.nombreUsuario = nombreUsuario;
            this.tipoUsuario = tipoUsuario;
            this.contraseña = contraseña;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WebServiceNuevoUsuarioResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class WebServiceNuevoUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] @return;
        
        public WebServiceNuevoUsuarioResponse() {
        }
        
        public WebServiceNuevoUsuarioResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceUsuarioChannel : ServiExpress.WebServiceUsuario.WebServiceUsuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceUsuarioClient : System.ServiceModel.ClientBase<ServiExpress.WebServiceUsuario.WebServiceUsuario>, ServiExpress.WebServiceUsuario.WebServiceUsuario {
        
        public WebServiceUsuarioClient() {
        }
        
        public WebServiceUsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceUsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceUsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceUsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiExpress.WebServiceUsuario.WebServiceNuevoUsuarioResponse ServiExpress.WebServiceUsuario.WebServiceUsuario.WebServiceNuevoUsuario(ServiExpress.WebServiceUsuario.WebServiceNuevoUsuarioRequest request) {
            return base.Channel.WebServiceNuevoUsuario(request);
        }
        
        public string[] WebServiceNuevoUsuario(string rut, string primerNombre, string segundoNombre, string apellidoPaterno, string apellidoMaterno, int telefono, string email, string direccion, int comuna, string nombreUsuario, int tipoUsuario, string contraseña) {
            ServiExpress.WebServiceUsuario.WebServiceNuevoUsuarioRequest inValue = new ServiExpress.WebServiceUsuario.WebServiceNuevoUsuarioRequest();
            inValue.rut = rut;
            inValue.primerNombre = primerNombre;
            inValue.segundoNombre = segundoNombre;
            inValue.apellidoPaterno = apellidoPaterno;
            inValue.apellidoMaterno = apellidoMaterno;
            inValue.telefono = telefono;
            inValue.email = email;
            inValue.direccion = direccion;
            inValue.comuna = comuna;
            inValue.nombreUsuario = nombreUsuario;
            inValue.tipoUsuario = tipoUsuario;
            inValue.contraseña = contraseña;
            ServiExpress.WebServiceUsuario.WebServiceNuevoUsuarioResponse retVal = ((ServiExpress.WebServiceUsuario.WebServiceUsuario)(this)).WebServiceNuevoUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiExpress.WebServiceUsuario.WebServiceNuevoUsuarioResponse> ServiExpress.WebServiceUsuario.WebServiceUsuario.WebServiceNuevoUsuarioAsync(ServiExpress.WebServiceUsuario.WebServiceNuevoUsuarioRequest request) {
            return base.Channel.WebServiceNuevoUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiExpress.WebServiceUsuario.WebServiceNuevoUsuarioResponse> WebServiceNuevoUsuarioAsync(string rut, string primerNombre, string segundoNombre, string apellidoPaterno, string apellidoMaterno, int telefono, string email, string direccion, int comuna, string nombreUsuario, int tipoUsuario, string contraseña) {
            ServiExpress.WebServiceUsuario.WebServiceNuevoUsuarioRequest inValue = new ServiExpress.WebServiceUsuario.WebServiceNuevoUsuarioRequest();
            inValue.rut = rut;
            inValue.primerNombre = primerNombre;
            inValue.segundoNombre = segundoNombre;
            inValue.apellidoPaterno = apellidoPaterno;
            inValue.apellidoMaterno = apellidoMaterno;
            inValue.telefono = telefono;
            inValue.email = email;
            inValue.direccion = direccion;
            inValue.comuna = comuna;
            inValue.nombreUsuario = nombreUsuario;
            inValue.tipoUsuario = tipoUsuario;
            inValue.contraseña = contraseña;
            return ((ServiExpress.WebServiceUsuario.WebServiceUsuario)(this)).WebServiceNuevoUsuarioAsync(inValue);
        }
    }
}
